### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by mauvm** [kukua/concava-connector-spul#2]
When inserting 15,000 records, the memory usage climbed from ~140MB to ~165MB. Debug this possible memory leak. It may also be that Docker uses memory for its logs.

**Comment by SodaqMoja** [comment]
Not sure if this is the same but I get:

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Aborted (core dumped)
```

I'll send you the (docker) log that I have

**Comment by SodaqMoja** [comment]
Oh, it is probably that I did not update the docker image

**Comment by SodaqMoja** [comment]
Hmm with v0.8.0 I'm still getting the same error

```
> concava-connector-spul@0.8.0 start /data
> node lib/connector.js

{"name":"concava-connector-spul","hostname":"45b693abd7da","pid":18,"level":50,"type":"uncaught-exception","stack":"Error: read ETIMEDOUT\n    at exports._errnoException (util.js:874:11)\n    at TCP.onread (net.js:544:26)","msg":"Error: read ETIMEDOUT","time":"2016-04-30T18:02:05.958Z","v":0}

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

**Comment by mauvm** [comment]
This also happened in v0.7? I haven't seen this before and can only imagine that by not closing the socket in the connector, some variables are kept in memory, which causes a memory leak.

In the other log you've send me I saw that the SPUL connector uses ~1.4GB of RAM. This is a lot, since it normally uses ~65MB. Also unfortunately the `ETIMEDOUT` error still occurs.

I will be adding a `DEBUG` option today that'll log extensive (connection) information. This hopefully gives us some insights.
FYI: the logs are now handled by Bunyan and can be found in `/logs/info.log` (v0.8) or `/spul.log` (v0.9+).

**Comment by mauvm** [comment]
@SodaqMoja Also: any thoughts on adding a timeout to the SPUL connector? Say: close socket after 30 seconds?

**Comment by mauvm** [comment]
v0.9 is now running on `spul.kukua.tech` and `d.kukua.cc`. It appears that the connections aren't closed properly. I see the total amount of connections increasing and no disconnects.

**Comment by SodaqMoja** [comment]
I don't know about the timeout. It is strange that the server does not see the close.
Maybe the GPRS device tell me the socket is closed, but in reality it may be so that it has to negotiate this close with the server. I'll have to skim through the GPRS device manual to see if something like that could be happening.
Meanwhile a timeout of 30 seconds sounds good to me.

**Comment by mauvm** [comment]
Since yesterday around 14:00 up until now the SPUL connector has 535 open sockets. However the memory usage rose from ~44MB to only ~51MB. This is on `d.kukua.cc`.

**Comment by mauvm** [comment]
v0.10 is now running on spul.kukua.tech and d.kukua.cc. See `.env.sample` for the latest configuration options.

**Comment by SodaqMoja** [comment]
I stopped running my own SPUL connector.
It keeps running into
    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
This is with 0.10.0

I'm using d.kukua.cc right now. Let's see how that holds up ...
